In [57]:
pip install gdown

Requirement already satisfied: gdown in c:\users\nessp\anaconda3\lib\site-packages (5.2.0)
Requirement already satisfied: beautifulsoup4 in c:\users\nessp\anaconda3\lib\site-packages (from gdown) (4.12.3)
Requirement already satisfied: filelock in c:\users\nessp\anaconda3\lib\site-packages (from gdown) (3.13.1)
Requirement already satisfied: requests[socks] in c:\users\nessp\anaconda3\lib\site-packages (from gdown) (2.32.2)
Requirement already satisfied: tqdm in c:\users\nessp\anaconda3\lib\site-packages (from gdown) (4.66.4)
Requirement already satisfied: soupsieve>1.2 in c:\users\nessp\anaconda3\lib\site-packages (from beautifulsoup4->gdown) (2.5)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\nessp\anaconda3\lib\site-packages (from requests[socks]->gdown) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\nessp\anaconda3\lib\site-packages (from requests[socks]->gdown) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\nessp\anaconda3\lib\site-packages (from requests[socks]->gdown) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\nessp\anaconda3\lib\site-packages (from requests[socks]->gdown) (2024.8.30)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in c:\users\nessp\anaconda3\lib\site-packages (from requests[socks]->gdown) (1.7.1)
Requirement already satisfied: colorama in c:\users\nessp\anaconda3\lib\site-packages (from tqdm->gdown) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [58]:
import gdown

In [59]:
import pandas as pd
# Chargement du fichier CSV
# ID du fichier
file_id = '1VB5_gl1fnyBDzcIOXZ5vUSbCY68VZN1v'
# Générer l'URL de téléchargement
url = f'https://drive.google.com/uc?id={file_id}'
output = 'df.csv'
# Télécharger le fichier CSV
gdown.download(url, output, quiet=False)

Downloading...
From (original): https://drive.google.com/uc?id=1VB5_gl1fnyBDzcIOXZ5vUSbCY68VZN1v
From (redirected): https://drive.google.com/uc?id=1VB5_gl1fnyBDzcIOXZ5vUSbCY68VZN1v&confirm=t&uuid=b2822beb-be30-437d-903a-82973d424b4d
To: c:\Users\nessp\OneDrive\Desktop\df.csv
100%|██████████| 157M/157M [00:34<00:00, 4.48MB/s]

'df.csv'

In [60]:
import pandas as pd

# Supposons que df soit votre DataFrame initial

# Filtrer les lignes contenant 'US' dans la colonne production_companies_name
filtered_df = df[df['production_companies_country'].str.contains('US', na=False, case=False)]

# Afficher le DataFrame filtré
display(filtered_df)

,adult,backdrop_path,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,production_companies_name,production_companies_country
0,False,/dvQj1GBZAZirz1skEEZyWH2ZqQP.jpg,0,['Comedy'],NaN,3924,tt0029927,en,Blondie,Blondie and Dagwood are about to celebrate the...,...,70,['en'],Released,The favorite comic strip of millions at last o...,Blondie,False,7.214,7,['Columbia Pictures'],['US']
5,False,/c1BaOxC8bo5ACFYkYYxL0bBWRaq.jpg,4000000,"['Crime', 'Comedy']",https://www.miramax.com/movie/four-rooms/,5,tt0113101,en,Four Rooms,It's Ted the Bellhop's first night on the job....,...,98,['en'],Released,Twelve outrageous guests. Four scandalous requ...,Four Rooms,False,5.758,2357,"['Miramax', 'A Band Apart']","['US', 'US']"
6,False,/bGMqHn0H2UY6SPZ5Vch4YJM2jDO.jpg,21000000,"['Action', 'Crime', 'Thriller']",NaN,6,tt0107286,en,Judgment Night,"While racing to a boxing match, Frank, Mike, J...",...,109,['en'],Released,Don't move. Don't whisper. Don't even breathe.,Judgment Night,False,6.600,284,"['Largo Entertainment', 'JVC']","['US', 'JP']"
9,False,/2w4xG178RpB4MDAIfTkqAuSJzec.jpg,11000000,"['Adventure', 'Action', 'Science Fiction']",http://www.starwars.com/films/star-wars-episod...,11,tt0076759,en,Star Wars,Princess Leia is captured and held hostage by ...,...,121,['en'],Released,"A long time ago in a galaxy far, far away...",Star Wars,False,8.208,18582,"['Lucasfilm Ltd.', '20th Century Fox']","['US', 'US']"
10,False,/yzqaKAhglTrkeOfuIXYYArf0WnA.jpg,94000000,"['Animation', 'Family']",http://movies.disney.com/finding-nemo,12,tt0266543,en,Finding Nemo,"Nemo, an adventurous young clownfish, is unexp...",...,100,['en'],Released,There are 3.7 trillion fish in the ocean. They...,Finding Nemo,False,7.823,17625,['Pixar'],['US']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164337,False,NaN,0,['Mystery'],NaN,1057081,tt0010761,en,The Teeth of the Tiger,Living quietly under the assumed name Paul Ser...,...,60,['xx'],Released,NaN,The Teeth of the Tiger,False,0.000,0,['Paramount'],['US']
164338,False,NaN,0,"['Crime', 'Mystery']",NaN,1057073,tt0167005,en,Arsene Lupin,Story of the gentleman thief.,...,50,['xx'],Released,NaN,Arsene Lupin,False,0.000,0,['Vitagraph Company of America'],['US']
164342,False,NaN,0,['Crime'],NaN,1057065,tt0366510,en,The Gentleman Burglar,The Proposal: The gentleman burglar walking wi...,...,0,['xx'],Released,NaN,The Gentleman Burglar,False,0.000,0,['Edison Studios'],['US']
164383,False,NaN,0,['Thriller'],NaN,1056841,tt12209830,en,A Rare Grand Alignment,Directed by Cinqué Lee. Plot currently unknown.,...,0,"['en', 'fi', 'no']",In Production,NaN,A Rare Grand Alignment,False,0.000,0,"['Fireframe', 'Bass Violin Productions', 'Fuzz...","['FI', 'US', 'US']"
164391,False,NaN,0,['Animation'],https://www.baobabstudios.com/bonfire,1056786,tt9899790,en,Bonfire,You’ve just crashed your spaceship on a strang...,...,15,[],Released,NaN,Bonfire,False,0.000,0,"['Baobab Studios', 'Pollen Music Group']","['US', 'US']"

In [61]:
filtered_df.shape

(23590, 25)

In [62]:
# Filtrer les lignes contenant 'US' dans la colonne production_companies_name
filtered_df = df[df['spoken_languages'].str.contains('fr', na=False, case=False)]

# Afficher le DataFrame filtré
display(filtered_df)

,adult,backdrop_path,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,production_companies_name,production_companies_country
2,False,/uJlc4aNPF3Y8yAqahJTKBwgwPVW.jpg,0,"['Drama', 'Romance']",NaN,8773,tt0055747,fr,L'Amour à vingt ans,Love at Twenty unites five directors from five...,...,110,"['it', 'ja', 'pl', 'fr', 'de']",Released,The Intimate Secrets of Young Lovers,Love at Twenty,False,6.700,41,"['Ulysse Productions', 'Unitec Films', 'Cinese...","['', 'NZ', 'IT', 'JP', 'DE', 'PL', '']"
21,False,/lVy5Zqcty2NfemqKYbVJfdg44rK.jpg,30000000,"['Action', 'Crime']",http://www.miramax.com/movie/kill-bill-volume-1,24,tt0266697,en,Kill Bill: Vol. 1,"An assassin is shot by her ruthless employer, ...",...,111,"['en', 'ja', 'fr']",Released,A roaring rampage of revenge.,Kill Bill: Vol. 1,False,7.970,15748,"['Miramax', 'A Band Apart', 'Super Cool ManChu']","['US', 'US', '']"
25,False,/9Qs9oyn4iE8QtQjGZ0Hp2WyYNXT.jpg,31500000,"['Drama', 'War']",http://www.apocalypsenow.com,28,tt0078788,en,Apocalypse Now,"At the height of the Vietnam war, Captain Benj...",...,147,"['km', 'en', 'fr', 'vi']",Released,This is the end...,Apocalypse Now,False,8.281,7199,"['United Artists', 'American Zoetrope']","['US', 'US']"
33,False,/1IWaKG7AWiYMhADxhGtnElDJAGI.jpg,29000000,"['Science Fiction', 'Thriller', 'Mystery']",NaN,63,tt0114746,en,Twelve Monkeys,"In the year 2035, convict James Cole reluctant...",...,129,"['en', 'fr']",Released,The future is history.,Twelve Monkeys,False,7.596,7444,"['Universal Pictures', 'Atlas Entertainment', ...","['US', 'US', '']"
44,False,/ELsTifJ2lu4vsMhoHeZ5EnncHw.jpg,70000000,"['Comedy', 'Fantasy', 'Science Fiction']",https://www.warnerbros.com/movies/mars-attacks/,75,tt0116996,en,Mars Attacks!,A fleet of Martian spacecraft surrounds the wo...,...,106,"['en', 'fr']",Released,Nice planet. We'll take it!,Mars Attacks!,False,6.394,4864,"['Tim Burton Productions', 'Warner Bros. Pictu...","['', 'US']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309024,False,NaN,0,['Documentary'],NaN,231361,tt1741561,fr,Panorama pris d'un ballon captif,Street scene shot from a balloon.,...,1,['fr'],Released,NaN,Panorama pris d'un ballon captif,False,5.300,6,['Lumière'],NaN
309278,False,/weanMzu1Gufj1dzOPCXljONZhRX.jpg,0,['Documentary'],NaN,232230,tt1331091,fr,Au loin des villages,Since the conflict in Darfur spread to the eas...,...,75,"['fr', 'it']",Released,NaN,Far from the Villages,False,0.000,0,"['Prince Film SA', 'AMIP', 'Les Films du Mélan...",NaN
309283,False,/A94D7d8LaPjpSV3uiP82ZbbS30F.jpg,0,['Comedy'],NaN,232251,tt0167083,cs,"Co je doma to se počítá, pánové...",Czech comedy from the 70ties.,...,84,"['en', 'cs', 'fr', 'de']",Released,NaN,"Co je doma to se počítá, pánové...",False,6.800,6,['Filmové studio Barrandov'],NaN
309333,False,NaN,0,['Music'],NaN,232577,tt0262231,fr,"Anna, qu'est-ce que t'attends?",Modern Americans think that the movies learned...,...,2,['fr'],Released,NaN,"Anna, what are you waiting for?",False,5.000,3,[],NaN
309433,False,NaN,0,['Documentary'],NaN,232932,tt1442625,fr,Le chemin noir,NaN,...,0,['fr'],Released,NaN,Le chemin noir,False,0.000,0,['La Vie Est Belle Films Associés'],NaN

In [63]:
# Supprimer les lignes où vote_count est égal à 0
filtered_df = filtered_df[filtered_df['vote_average'] != 0]

# Réinitialiser les index après suppression (optionnel)
filtered_df.reset_index(drop=True, inplace=True)

# Afficher le DataFrame mis à jour
display(filtered_df)

,adult,backdrop_path,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,production_companies_name,production_companies_country
0,False,/uJlc4aNPF3Y8yAqahJTKBwgwPVW.jpg,0,"['Drama', 'Romance']",NaN,8773,tt0055747,fr,L'Amour à vingt ans,Love at Twenty unites five directors from five...,...,110,"['it', 'ja', 'pl', 'fr', 'de']",Released,The Intimate Secrets of Young Lovers,Love at Twenty,False,6.700,41,"['Ulysse Productions', 'Unitec Films', 'Cinese...","['', 'NZ', 'IT', 'JP', 'DE', 'PL', '']"
1,False,/lVy5Zqcty2NfemqKYbVJfdg44rK.jpg,30000000,"['Action', 'Crime']",http://www.miramax.com/movie/kill-bill-volume-1,24,tt0266697,en,Kill Bill: Vol. 1,"An assassin is shot by her ruthless employer, ...",...,111,"['en', 'ja', 'fr']",Released,A roaring rampage of revenge.,Kill Bill: Vol. 1,False,7.970,15748,"['Miramax', 'A Band Apart', 'Super Cool ManChu']","['US', 'US', '']"
2,False,/9Qs9oyn4iE8QtQjGZ0Hp2WyYNXT.jpg,31500000,"['Drama', 'War']",http://www.apocalypsenow.com,28,tt0078788,en,Apocalypse Now,"At the height of the Vietnam war, Captain Benj...",...,147,"['km', 'en', 'fr', 'vi']",Released,This is the end...,Apocalypse Now,False,8.281,7199,"['United Artists', 'American Zoetrope']","['US', 'US']"
3,False,/1IWaKG7AWiYMhADxhGtnElDJAGI.jpg,29000000,"['Science Fiction', 'Thriller', 'Mystery']",NaN,63,tt0114746,en,Twelve Monkeys,"In the year 2035, convict James Cole reluctant...",...,129,"['en', 'fr']",Released,The future is history.,Twelve Monkeys,False,7.596,7444,"['Universal Pictures', 'Atlas Entertainment', ...","['US', 'US', '']"
4,False,/ELsTifJ2lu4vsMhoHeZ5EnncHw.jpg,70000000,"['Comedy', 'Fantasy', 'Science Fiction']",https://www.warnerbros.com/movies/mars-attacks/,75,tt0116996,en,Mars Attacks!,A fleet of Martian spacecraft surrounds the wo...,...,106,"['en', 'fr']",Released,Nice planet. We'll take it!,Mars Attacks!,False,6.394,4864,"['Tim Burton Productions', 'Warner Bros. Pictu...","['', 'US']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16940,False,NaN,0,['Drama'],http://www.cuartocreciente.es/holden,230023,tt2371345,en,Holden,"Holden, a young photographer with a short-term...",...,20,"['fr', 'es']",Released,NaN,Holden,False,4.700,3,"['Cuarto Creciente', 'Monumental Studio']",NaN
16941,False,NaN,0,"['Crime', 'Science Fiction', 'Thriller']",NaN,230352,tt0138126,fr,Le temps de mourir,The movie starts with a mysterious girl riding...,...,80,['fr'],Released,NaN,The Time to Die,False,4.900,7,['Les Films de la Licorne'],NaN
16942,False,NaN,0,['Documentary'],NaN,231361,tt1741561,fr,Panorama pris d'un ballon captif,Street scene shot from a balloon.,...,1,['fr'],Released,NaN,Panorama pris d'un ballon captif,False,5.300,6,['Lumière'],NaN
16943,False,/A94D7d8LaPjpSV3uiP82ZbbS30F.jpg,0,['Comedy'],NaN,232251,tt0167083,cs,"Co je doma to se počítá, pánové...",Czech comedy from the 70ties.,...,84,"['en', 'cs', 'fr', 'de']",Released,NaN,"Co je doma to se počítá, pánové...",False,6.800,6,['Filmové studio Barrandov'],NaN
16944,False,NaN,0,['Music'],NaN,232577,tt0262231,fr,"Anna, qu'est-ce que t'attends?",Modern Americans think that the movies learned...,...,2,['fr'],Released,NaN,"Anna, what are you waiting for?",False,5.000,3,[],NaN

In [64]:
# Calcul de la moyenne de la colonne 'vote_average'
moyenne_vote_average = filtered_df['vote_average'].mean()

# Filtrer les lignes où 'vote_average' est supérieur ou égal à la moyenne
filtered_df = filtered_df[filtered_df['vote_average'] >= moyenne_vote_average]

# Réinitialiser les index après la suppression (optionnel)
filtered_df.reset_index(drop=True, inplace=True)

# Afficher le DataFrame filtré
display(filtered_df)

,adult,backdrop_path,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,production_companies_name,production_companies_country
0,False,/uJlc4aNPF3Y8yAqahJTKBwgwPVW.jpg,0,"['Drama', 'Romance']",NaN,8773,tt0055747,fr,L'Amour à vingt ans,Love at Twenty unites five directors from five...,...,110,"['it', 'ja', 'pl', 'fr', 'de']",Released,The Intimate Secrets of Young Lovers,Love at Twenty,False,6.700,41,"['Ulysse Productions', 'Unitec Films', 'Cinese...","['', 'NZ', 'IT', 'JP', 'DE', 'PL', '']"
1,False,/lVy5Zqcty2NfemqKYbVJfdg44rK.jpg,30000000,"['Action', 'Crime']",http://www.miramax.com/movie/kill-bill-volume-1,24,tt0266697,en,Kill Bill: Vol. 1,"An assassin is shot by her ruthless employer, ...",...,111,"['en', 'ja', 'fr']",Released,A roaring rampage of revenge.,Kill Bill: Vol. 1,False,7.970,15748,"['Miramax', 'A Band Apart', 'Super Cool ManChu']","['US', 'US', '']"
2,False,/9Qs9oyn4iE8QtQjGZ0Hp2WyYNXT.jpg,31500000,"['Drama', 'War']",http://www.apocalypsenow.com,28,tt0078788,en,Apocalypse Now,"At the height of the Vietnam war, Captain Benj...",...,147,"['km', 'en', 'fr', 'vi']",Released,This is the end...,Apocalypse Now,False,8.281,7199,"['United Artists', 'American Zoetrope']","['US', 'US']"
3,False,/1IWaKG7AWiYMhADxhGtnElDJAGI.jpg,29000000,"['Science Fiction', 'Thriller', 'Mystery']",NaN,63,tt0114746,en,Twelve Monkeys,"In the year 2035, convict James Cole reluctant...",...,129,"['en', 'fr']",Released,The future is history.,Twelve Monkeys,False,7.596,7444,"['Universal Pictures', 'Atlas Entertainment', ...","['US', 'US', '']"
4,False,/ELsTifJ2lu4vsMhoHeZ5EnncHw.jpg,70000000,"['Comedy', 'Fantasy', 'Science Fiction']",https://www.warnerbros.com/movies/mars-attacks/,75,tt0116996,en,Mars Attacks!,A fleet of Martian spacecraft surrounds the wo...,...,106,"['en', 'fr']",Released,Nice planet. We'll take it!,Mars Attacks!,False,6.394,4864,"['Tim Burton Productions', 'Warner Bros. Pictu...","['', 'US']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8639,False,NaN,0,"['Drama', 'Fantasy']",NaN,227222,tt3101756,fr,Twaaga,Burkina Faso in 1987 is a country in the throe...,...,32,"['ar', 'fr']",Released,NaN,Invincible,False,8.000,1,['CNC'],NaN
8640,False,NaN,0,"['Documentary', 'Drama']",NaN,228118,tt3102838,fr,Tableau noir,Documentary following the last year of a small...,...,117,['fr'],Released,NaN,Tableau noir,False,8.100,4,[],NaN
8641,False,/9AkWQSb5Zj5NlYRXipw4f4WHtgr.jpg,0,"['Music', 'Documentary']",NaN,228234,tt0798733,en,Retour à Gorée,Because jazz is the miraculous product of the ...,...,110,"['en', 'fr']",Released,NaN,Return to Gorée,False,9.000,1,"['Iris Productions', 'CAB Productions', 'Dream...",NaN
8642,False,/x3tXDViQGjkEpEoC5VlcBhwEGcv.jpg,13500,['Drama'],NaN,228302,tt1127836,fr,13 ans,"Jonathan is in love with Julie, the most beaut...",...,11,['fr'],Released,NaN,My 13,False,7.600,13,[],NaN
8643,False,/A94D7d8LaPjpSV3uiP82ZbbS30F.jpg,0,['Comedy'],NaN,232251,tt0167083,cs,"Co je doma to se počítá, pánové...",Czech comedy from the 70ties.,...,84,"['en', 'cs', 'fr', 'de']",Released,NaN,"Co je doma to se počítá, pánové...",False,6.800,6,['Filmové studio Barrandov'],NaN

In [65]:
filtered_df.shape

(8644, 25)

In [67]:
# Supprimer les doublons basés sur la colonne 'imdb_id'
filtered_df = filtered_df.drop_duplicates(subset='imdb_id')

# Réinitialiser l'index après suppression (optionnel)
filtered_df.reset_index(drop=True, inplace=True)

# Afficher le DataFrame sans doublons
display(filtered_df)

,adult,backdrop_path,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,production_companies_name,production_companies_country
0,False,/uJlc4aNPF3Y8yAqahJTKBwgwPVW.jpg,0,"['Drama', 'Romance']",NaN,8773,tt0055747,fr,L'Amour à vingt ans,Love at Twenty unites five directors from five...,...,110,"['it', 'ja', 'pl', 'fr', 'de']",Released,The Intimate Secrets of Young Lovers,Love at Twenty,False,6.700,41,"['Ulysse Productions', 'Unitec Films', 'Cinese...","['', 'NZ', 'IT', 'JP', 'DE', 'PL', '']"
1,False,/lVy5Zqcty2NfemqKYbVJfdg44rK.jpg,30000000,"['Action', 'Crime']",http://www.miramax.com/movie/kill-bill-volume-1,24,tt0266697,en,Kill Bill: Vol. 1,"An assassin is shot by her ruthless employer, ...",...,111,"['en', 'ja', 'fr']",Released,A roaring rampage of revenge.,Kill Bill: Vol. 1,False,7.970,15748,"['Miramax', 'A Band Apart', 'Super Cool ManChu']","['US', 'US', '']"
2,False,/9Qs9oyn4iE8QtQjGZ0Hp2WyYNXT.jpg,31500000,"['Drama', 'War']",http://www.apocalypsenow.com,28,tt0078788,en,Apocalypse Now,"At the height of the Vietnam war, Captain Benj...",...,147,"['km', 'en', 'fr', 'vi']",Released,This is the end...,Apocalypse Now,False,8.281,7199,"['United Artists', 'American Zoetrope']","['US', 'US']"
3,False,/1IWaKG7AWiYMhADxhGtnElDJAGI.jpg,29000000,"['Science Fiction', 'Thriller', 'Mystery']",NaN,63,tt0114746,en,Twelve Monkeys,"In the year 2035, convict James Cole reluctant...",...,129,"['en', 'fr']",Released,The future is history.,Twelve Monkeys,False,7.596,7444,"['Universal Pictures', 'Atlas Entertainment', ...","['US', 'US', '']"
4,False,/ELsTifJ2lu4vsMhoHeZ5EnncHw.jpg,70000000,"['Comedy', 'Fantasy', 'Science Fiction']",https://www.warnerbros.com/movies/mars-attacks/,75,tt0116996,en,Mars Attacks!,A fleet of Martian spacecraft surrounds the wo...,...,106,"['en', 'fr']",Released,Nice planet. We'll take it!,Mars Attacks!,False,6.394,4864,"['Tim Burton Productions', 'Warner Bros. Pictu...","['', 'US']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8639,False,NaN,0,"['Drama', 'Fantasy']",NaN,227222,tt3101756,fr,Twaaga,Burkina Faso in 1987 is a country in the throe...,...,32,"['ar', 'fr']",Released,NaN,Invincible,False,8.000,1,['CNC'],NaN
8640,False,NaN,0,"['Documentary', 'Drama']",NaN,228118,tt3102838,fr,Tableau noir,Documentary following the last year of a small...,...,117,['fr'],Released,NaN,Tableau noir,False,8.100,4,[],NaN
8641,False,/9AkWQSb5Zj5NlYRXipw4f4WHtgr.jpg,0,"['Music', 'Documentary']",NaN,228234,tt0798733,en,Retour à Gorée,Because jazz is the miraculous product of the ...,...,110,"['en', 'fr']",Released,NaN,Return to Gorée,False,9.000,1,"['Iris Productions', 'CAB Productions', 'Dream...",NaN
8642,False,/x3tXDViQGjkEpEoC5VlcBhwEGcv.jpg,13500,['Drama'],NaN,228302,tt1127836,fr,13 ans,"Jonathan is in love with Julie, the most beaut...",...,11,['fr'],Released,NaN,My 13,False,7.600,13,[],NaN
8643,False,/A94D7d8LaPjpSV3uiP82ZbbS30F.jpg,0,['Comedy'],NaN,232251,tt0167083,cs,"Co je doma to se počítá, pánové...",Czech comedy from the 70ties.,...,84,"['en', 'cs', 'fr', 'de']",Released,NaN,"Co je doma to se počítá, pánové...",False,6.800,6,['Filmové studio Barrandov'],NaN

In [68]:
filtered_df.shape

(8644, 25)

In [69]:
# Supprimer les colonnes spécifiques
filtered_df = filtered_df.drop(columns=['adult', 'budget', 'homepage', 'vote_count', 'production_companies_country'])

# Afficher le DataFrame après suppression des colonnes
display(filtered_df)

,backdrop_path,genres,id,imdb_id,original_language,original_title,overview,popularity,poster_path,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,production_companies_name
0,/uJlc4aNPF3Y8yAqahJTKBwgwPVW.jpg,"['Drama', 'Romance']",8773,tt0055747,fr,L'Amour à vingt ans,Love at Twenty unites five directors from five...,3.770,/aup2QCYCsyEeQfpboXy0f4uj8aE.jpg,"['DE', 'FR', 'IT', 'JP', 'PL']",1962-06-22,0,110,"['it', 'ja', 'pl', 'fr', 'de']",Released,The Intimate Secrets of Young Lovers,Love at Twenty,False,6.700,"['Ulysse Productions', 'Unitec Films', 'Cinese..."
1,/lVy5Zqcty2NfemqKYbVJfdg44rK.jpg,"['Action', 'Crime']",24,tt0266697,en,Kill Bill: Vol. 1,"An assassin is shot by her ruthless employer, ...",31.556,/v7TaX8kXMXs5yFFGR41guUDNcnB.jpg,['US'],2003-10-10,180906076,111,"['en', 'ja', 'fr']",Released,A roaring rampage of revenge.,Kill Bill: Vol. 1,False,7.970,"['Miramax', 'A Band Apart', 'Super Cool ManChu']"
2,/9Qs9oyn4iE8QtQjGZ0Hp2WyYNXT.jpg,"['Drama', 'War']",28,tt0078788,en,Apocalypse Now,"At the height of the Vietnam war, Captain Benj...",31.785,/gQB8Y5RCMkv2zwzFHbUJX3kAhvA.jpg,['US'],1979-08-15,150000000,147,"['km', 'en', 'fr', 'vi']",Released,This is the end...,Apocalypse Now,False,8.281,"['United Artists', 'American Zoetrope']"
3,/1IWaKG7AWiYMhADxhGtnElDJAGI.jpg,"['Science Fiction', 'Thriller', 'Mystery']",63,tt0114746,en,Twelve Monkeys,"In the year 2035, convict James Cole reluctant...",29.184,/gt3iyguaCIw8DpQZI1LIN5TohM2.jpg,['US'],1995-12-29,168841459,129,"['en', 'fr']",Released,The future is history.,Twelve Monkeys,False,7.596,"['Universal Pictures', 'Atlas Entertainment', ..."
4,/ELsTifJ2lu4vsMhoHeZ5EnncHw.jpg,"['Comedy', 'Fantasy', 'Science Fiction']",75,tt0116996,en,Mars Attacks!,A fleet of Martian spacecraft surrounds the wo...,21.051,/hll4O5vSAfnZDb6JbnP06GPtz7b.jpg,['US'],1996-12-12,101371017,106,"['en', 'fr']",Released,Nice planet. We'll take it!,Mars Attacks!,False,6.394,"['Tim Burton Productions', 'Warner Bros. Pictu..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8639,NaN,"['Drama', 'Fantasy']",227222,tt3101756,fr,Twaaga,Burkina Faso in 1987 is a country in the throe...,0.600,NaN,"['BF', 'FR']",2013-10-12,0,32,"['ar', 'fr']",Released,NaN,Invincible,False,8.000,['CNC']
8640,NaN,"['Documentary', 'Drama']",228118,tt3102838,fr,Tableau noir,Documentary following the last year of a small...,0.600,/dgPNp3onm5yA69OPESRtBvw6asz.jpg,[],2013-10-02,0,117,['fr'],Released,NaN,Tableau noir,False,8.100,[]
8641,/9AkWQSb5Zj5NlYRXipw4f4WHtgr.jpg,"['Music', 'Documentary']",228234,tt0798733,en,Retour à Gorée,Because jazz is the miraculous product of the ...,0.875,/sxWUP8ejWPNAdUzFsJN3pBUaVet.jpg,"['LU', 'CH']",2007-10-27,0,110,"['en', 'fr']",Released,NaN,Return to Gorée,False,9.000,"['Iris Productions', 'CAB Productions', 'Dream..."
8642,/x3tXDViQGjkEpEoC5VlcBhwEGcv.jpg,['Drama'],228302,tt1127836,fr,13 ans,"Jonathan is in love with Julie, the most beaut...",1.860,/ui8G6N1GmEMc27DeDosmhFOpRMN.jpg,['FR'],2008-02-04,0,11,['fr'],Released,NaN,My 13,False,7.600,[]
8643,/A94D7d8LaPjpSV3uiP82ZbbS30F.jpg,['Comedy'],232251,tt0167083,cs,"Co je doma to se počítá, pánové...",Czech comedy from the 70ties.,1.067,/lDwd3ixq5Ou8dFAQEd2xOAESHtE.jpg,['XC'],1980-11-01,0,84,"['en', 'cs', 'fr', 'de']",Released,NaN,"Co je doma to se počítá, pánové...",False,6.800,['Filmové studio Barrandov']

In [70]:
filtered_df.shape

(8644, 20)