In [1]:
pip install gdown

Requirement already satisfied: gdown in /usr/local/lib/python3.10/dist-packages (5.2.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from gdown) (4.12.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from gdown) (3.16.1)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.10/dist-packages (from gdown) (2.32.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from gdown) (4.66.6)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->gdown) (2.6)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (2024.8.30)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (1.7.1)

In [2]:
from datetime import datetime
from datetime import timedelta
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import gdown

In [4]:
# ID du fichier Google Drive
file_id_tmdb = '1SSeKdAQQqU6QbWwKfiKNcqNEqHxbwGm3'
url_tmdb = f'https://drive.google.com/uc?id={file_id_tmdb}'

# Chemin de sauvegarde du fichier téléchargé
output = 'tmdb.csv'

# Télécharger le fichier
gdown.download(url_tmdb, output, quiet=False)

# Lire le fichier CSV avec pandas
try:
    df_tmdb = pd.read_csv(output, delimiter=',', on_bad_lines='skip', engine='python')
    if df_tmdb.empty:
        print("Le fichier est vide.")
    else:
        # Afficher les premières lignes du DataFrame
        display(df_tmdb.head())
except pd.errors.EmptyDataError:
    print("Aucune donnée à analyser dans le fichier.")
except Exception as e:
    print(f"Une erreur est survenue : {e}")

Downloading...
From (original): https://drive.google.com/uc?id=1SSeKdAQQqU6QbWwKfiKNcqNEqHxbwGm3
From (redirected): https://drive.google.com/uc?id=1SSeKdAQQqU6QbWwKfiKNcqNEqHxbwGm3&confirm=t&uuid=78ef17d3-f965-4016-894e-813a9bd9e7f5
To: /content/tmdb.csv
100%|██████████| 157M/157M [00:00<00:00, 209MB/s]

,adult,backdrop_path,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,production_companies_name,production_companies_country
0,False,/dvQj1GBZAZirz1skEEZyWH2ZqQP.jpg,0,['Comedy'],NaN,3924,tt0029927,en,Blondie,Blondie and Dagwood are about to celebrate the...,...,70,['en'],Released,The favorite comic strip of millions at last o...,Blondie,False,7.214,7,['Columbia Pictures'],['US']
1,False,NaN,0,['Adventure'],NaN,6124,tt0011436,de,Der Mann ohne Namen,NaN,...,420,[],Released,NaN,"Peter Voss, Thief of Millions",False,0.000,0,[],[]
2,False,/uJlc4aNPF3Y8yAqahJTKBwgwPVW.jpg,0,"['Drama', 'Romance']",NaN,8773,tt0055747,fr,L'Amour à vingt ans,Love at Twenty unites five directors from five...,...,110,"['it', 'ja', 'pl', 'fr', 'de']",Released,The Intimate Secrets of Young Lovers,Love at Twenty,False,6.700,41,"['Ulysse Productions', 'Unitec Films', 'Cinese...","['', 'NZ', 'IT', 'JP', 'DE', 'PL', '']"
3,False,/hQ4pYsIbP22TMXOUdSfC2mjWrO0.jpg,0,"['Drama', 'Comedy', 'Crime']",NaN,2,tt0094675,fi,Ariel,Taisto Kasurinen is a Finnish coal miner whose...,...,73,['fi'],Released,NaN,Ariel,False,7.046,248,['Villealfa Filmproductions'],['FI']
4,False,/l94l89eMmFKh7na2a1u5q67VgNx.jpg,0,"['Drama', 'Comedy', 'Romance']",NaN,3,tt0092149,fi,Varjoja paratiisissa,"An episode in the life of Nikander, a garbage ...",...,76,['en'],Released,NaN,Shadows in Paradise,False,7.182,269,['Villealfa Filmproductions'],['FI']

In [5]:
df_tmdb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309572 entries, 0 to 309571
Data columns (total 25 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   adult                         309572 non-null  bool
 1   backdrop_path                 151760 non-null  object
 2   budget                        309572 non-null  int64
 3   genres                        309572 non-null  object
 4   homepage                      44262 non-null   object
 5   id                            309572 non-null  int64
 6   imdb_id                       309572 non-null  object
 7   original_language             309572 non-null  object
 8   original_title                309572 non-null  object
 9   overview                      282512 non-null  object
 10  popularity                    309572 non-null  float64
 11  poster_path                   264159 non-null  object
 12  production_countries          309572 non-null  object
 13  release_date                  301339 non-null  object
 14  revenue                       309572 non-null  int64
 15  runtime                       309572 non-null  int64
 16  spoken_languages              309572 non-null  object
 17  status                        309572 non-null  object
 18  tagline                       74573 non-null   object
 19  title                         309572 non-null  object
 20  video                         309572 non-null  bool
 21  vote_average                  309572 non-null  float64
 22  vote_count                    309572 non-null  int64
 23  production_companies_name     309572 non-null  object
 24  production_companies_country  164438 non-null  object
dtypes: bool(2), float64(2), int64(5), object(16)
memory usage: 54.9+ MB

In [6]:
# Vérifier un échantillon du contenu de la colonne 'genres'
print(df_tmdb['genres'].head())

0                        ['Comedy']
1                     ['Adventure']
2              ['Drama', 'Romance']
3      ['Drama', 'Comedy', 'Crime']
4    ['Drama', 'Comedy', 'Romance']
Name: genres, dtype: object

In [7]:
# Convertir chaque élément de la colonne 'genres' en une chaîne de caractères si nécessaire
# Supposons que chaque élément est une chaîne de caractères ou une liste de chaînes de caractères
# Vous pouvez ajuster la logique de conversion en fonction du contenu réel

def convert_genres(genres):
    if isinstance(genres, list):
        return ' '.join(genres)
    elif isinstance(genres, str):
        return genres
    else:
        return str(genres)

df_tmdb['genres'] = df_tmdb['genres'].apply(convert_genres)
# Vérifier que la conversion a réussi
print(df_tmdb['genres'].head())

0                        ['Comedy']
1                     ['Adventure']
2              ['Drama', 'Romance']
3      ['Drama', 'Comedy', 'Crime']
4    ['Drama', 'Comedy', 'Romance']
Name: genres, dtype: object

In [8]:
# Filtrer les lignes où 'genres' contient 'Adventure' ou 'Comedy'
df_tmdb_filtered = df_tmdb[df_tmdb['genres'].str.contains('Adventure|Comedy', na=False)]

# Afficher les 15 premières lignes du DataFrame filtré
display(df_tmdb_filtered.head(2))

,adult,backdrop_path,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,production_companies_name,production_companies_country
0,False,/dvQj1GBZAZirz1skEEZyWH2ZqQP.jpg,0,['Comedy'],NaN,3924,tt0029927,en,Blondie,Blondie and Dagwood are about to celebrate the...,...,70,['en'],Released,The favorite comic strip of millions at last o...,Blondie,False,7.214,7,['Columbia Pictures'],['US']
1,False,NaN,0,['Adventure'],NaN,6124,tt0011436,de,Der Mann ohne Namen,NaN,...,420,[],Released,NaN,"Peter Voss, Thief of Millions",False,0.000,0,[],[]

In [9]:
# Filtrer les lignes où 'spoken_languages' contient 'fr'
df_tmdb_fr = df_tmdb_filtered[df_tmdb_filtered['spoken_languages'].str.contains('fr', na=False)]
display(df_tmdb_fr)

,adult,backdrop_path,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,production_companies_name,production_companies_country
44,False,/ELsTifJ2lu4vsMhoHeZ5EnncHw.jpg,70000000,"['Comedy', 'Fantasy', 'Science Fiction']",https://www.warnerbros.com/movies/mars-attacks/,75,tt0116996,en,Mars Attacks!,A fleet of Martian spacecraft surrounds the wo...,...,106,"['en', 'fr']",Released,Nice planet. We'll take it!,Mars Attacks!,False,6.394,4864,"['Tim Burton Productions', 'Warner Bros. Pictu...","['', 'US']"
77,False,/2eBL3wXDZqemW8SJ1RNxqtx6bgJ.jpg,0,"['Comedy', 'Drama', 'Mystery']",NaN,109,tt0111507,fr,Trois couleurs : Blanc,Polish immigrant Karol Karol finds himself out...,...,92,"['fr', 'hu', 'pl']",Released,NaN,Three Colors: White,False,7.482,989,"['Le Studio Canal+', 'France 3 Cinéma', 'Eurim...","['FR', 'FR', 'FR', 'US']"
102,False,/oT9diLGD1cgPdvkxqHIJcuSXKUT.jpg,14600000,"['Romance', 'Fantasy', 'Drama', 'Comedy']",NaN,137,tt0107048,en,Groundhog Day,"A narcissistic TV weatherman, along with his a...",...,101,"['en', 'fr', 'it']",Released,He’s having the worst day of his life… Over an...,Groundhog Day,False,7.603,6963,['Columbia Pictures'],['US']
130,False,/9B3NnLM7Uct4eSB5Th9aqVQa8uT.jpg,0,"['Drama', 'Romance', 'Comedy']",NaN,166,tt0082100,fr,La Boum,A thirteen-year-old French girl deals with mov...,...,110,['fr'],Released,NaN,The Party,False,6.605,1019,"['Productions Marcel Dassault', 'Gaumont', 'Ga...","['FR', 'FR', 'FR']"
135,False,/3oNDTUxv2lLWMqt5R12A0vM5dBn.jpg,0,"['Comedy', 'Romance', 'Drama']",NaN,171,tt0083686,fr,La Boum 2,A young French teenage girl after moving to a ...,...,109,['fr'],Released,NaN,The Party 2,False,6.454,570,"['Productions Marcel Dassault', 'Gaumont', 'Ga...","['FR', 'FR', 'FR']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308128,False,NaN,0,"['Drama', 'Comedy']",NaN,225255,tt0468834,lb,Perl oder Pica,"October 1962, the height of the Cuban missile ...",...,90,"['fr', 'lb']",Released,NaN,Little Secrets,False,5.300,9,"['Red Lion', 'Amour Fou Filmproduktion']",NaN
308260,False,/z9kgYGIZbp4vI4LwOrMM4kCe1Je.jpg,0,"['Comedy', 'TV Movie']",NaN,226288,tt0313313,fr,Le Bourgeois gentilhomme,Le Bourgeois gentilhomme satirizes attempts at...,...,130,['fr'],Released,NaN,Would-Be Gentleman,False,0.000,0,['Office de Radiodiffusion Télévision Française'],NaN
308324,False,NaN,0,['Comedy'],NaN,226855,tt0277844,fr,Max en convalescence,"To reassure his fans, Max Linder has been film...",...,11,['fr'],Released,NaN,Max Is Convalescent,False,6.200,8,['Pathé Frères'],NaN
308413,False,NaN,0,"['Comedy', 'TV Movie']",NaN,227460,tt0303166,fr,Ubu Roi,Based on Alfredy Jarrry's 1896 play about a gr...,...,95,['fr'],Released,NaN,Ubu Roi,False,5.100,5,['Office de Radiodiffusion Télévision Française'],NaN
309283,False,/A94D7d8LaPjpSV3uiP82ZbbS30F.jpg,0,['Comedy'],NaN,232251,tt0167083,cs,"Co je doma to se počítá, pánové...",Czech comedy from the 70ties.,...,84,"['en', 'cs', 'fr', 'de']",Released,NaN,"Co je doma to se počítá, pánové...",False,6.800,6,['Filmové studio Barrandov'],NaN

In [10]:
# Obtenir les valeurs uniques dans la colonne 'original_language'
fr_en = df_tmdb_fr['original_language'].unique()
print(fr_en)

['en' 'fr' 'it' 'de' 'el' 'sv' 'cs' 'nl' 'ar' 'es' 'ro' 'ja' 'cn' 'sr'
 'bo' 'hi' 'da' 'pl' 'ru' 'he' 'is' 'tr' 'et' 'pt' 'eu' 'fi' 'uk' 'fa'
 'hu' 'ca' 'zh' 'no' 'lb' 'gd' 'ko' 'th' 'hy' 'ka' 'wo' 'cr' 'fo' 'ml'
 'sh' 'xx' 'id']

In [11]:
# Obtenir les valeurs uniques dans la colonne 'status'
stat = df_tmdb_fr['status'].unique()
print(stat)

['Released' 'Planned' 'In Production' 'Post Production']

In [12]:
# Filtrer les lignes où 'status' contient 'Released'
df_tmdb_fr = df_tmdb_fr[df_tmdb_fr['status'].str.contains('Released', na=False)]
display(df_tmdb_fr)

,adult,backdrop_path,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,production_companies_name,production_companies_country
44,False,/ELsTifJ2lu4vsMhoHeZ5EnncHw.jpg,70000000,"['Comedy', 'Fantasy', 'Science Fiction']",https://www.warnerbros.com/movies/mars-attacks/,75,tt0116996,en,Mars Attacks!,A fleet of Martian spacecraft surrounds the wo...,...,106,"['en', 'fr']",Released,Nice planet. We'll take it!,Mars Attacks!,False,6.394,4864,"['Tim Burton Productions', 'Warner Bros. Pictu...","['', 'US']"
77,False,/2eBL3wXDZqemW8SJ1RNxqtx6bgJ.jpg,0,"['Comedy', 'Drama', 'Mystery']",NaN,109,tt0111507,fr,Trois couleurs : Blanc,Polish immigrant Karol Karol finds himself out...,...,92,"['fr', 'hu', 'pl']",Released,NaN,Three Colors: White,False,7.482,989,"['Le Studio Canal+', 'France 3 Cinéma', 'Eurim...","['FR', 'FR', 'FR', 'US']"
102,False,/oT9diLGD1cgPdvkxqHIJcuSXKUT.jpg,14600000,"['Romance', 'Fantasy', 'Drama', 'Comedy']",NaN,137,tt0107048,en,Groundhog Day,"A narcissistic TV weatherman, along with his a...",...,101,"['en', 'fr', 'it']",Released,He’s having the worst day of his life… Over an...,Groundhog Day,False,7.603,6963,['Columbia Pictures'],['US']
130,False,/9B3NnLM7Uct4eSB5Th9aqVQa8uT.jpg,0,"['Drama', 'Romance', 'Comedy']",NaN,166,tt0082100,fr,La Boum,A thirteen-year-old French girl deals with mov...,...,110,['fr'],Released,NaN,The Party,False,6.605,1019,"['Productions Marcel Dassault', 'Gaumont', 'Ga...","['FR', 'FR', 'FR']"
135,False,/3oNDTUxv2lLWMqt5R12A0vM5dBn.jpg,0,"['Comedy', 'Romance', 'Drama']",NaN,171,tt0083686,fr,La Boum 2,A young French teenage girl after moving to a ...,...,109,['fr'],Released,NaN,The Party 2,False,6.454,570,"['Productions Marcel Dassault', 'Gaumont', 'Ga...","['FR', 'FR', 'FR']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308128,False,NaN,0,"['Drama', 'Comedy']",NaN,225255,tt0468834,lb,Perl oder Pica,"October 1962, the height of the Cuban missile ...",...,90,"['fr', 'lb']",Released,NaN,Little Secrets,False,5.300,9,"['Red Lion', 'Amour Fou Filmproduktion']",NaN
308260,False,/z9kgYGIZbp4vI4LwOrMM4kCe1Je.jpg,0,"['Comedy', 'TV Movie']",NaN,226288,tt0313313,fr,Le Bourgeois gentilhomme,Le Bourgeois gentilhomme satirizes attempts at...,...,130,['fr'],Released,NaN,Would-Be Gentleman,False,0.000,0,['Office de Radiodiffusion Télévision Française'],NaN
308324,False,NaN,0,['Comedy'],NaN,226855,tt0277844,fr,Max en convalescence,"To reassure his fans, Max Linder has been film...",...,11,['fr'],Released,NaN,Max Is Convalescent,False,6.200,8,['Pathé Frères'],NaN
308413,False,NaN,0,"['Comedy', 'TV Movie']",NaN,227460,tt0303166,fr,Ubu Roi,Based on Alfredy Jarrry's 1896 play about a gr...,...,95,['fr'],Released,NaN,Ubu Roi,False,5.100,5,['Office de Radiodiffusion Télévision Française'],NaN
309283,False,/A94D7d8LaPjpSV3uiP82ZbbS30F.jpg,0,['Comedy'],NaN,232251,tt0167083,cs,"Co je doma to se počítá, pánové...",Czech comedy from the 70ties.,...,84,"['en', 'cs', 'fr', 'de']",Released,NaN,"Co je doma to se počítá, pánové...",False,6.800,6,['Filmové studio Barrandov'],NaN

In [13]:
#supprimer les colonnes 'budget', 'id', 'vote_count' et 'revenue'
tmdb_1= df_tmdb_fr.drop(columns=['budget', 'id', 'vote_count', 'revenue'])
display(tmdb_1.head(2))

,adult,backdrop_path,genres,homepage,imdb_id,original_language,original_title,overview,popularity,poster_path,...,release_date,runtime,spoken_languages,status,tagline,title,video,vote_average,production_companies_name,production_companies_country
44,False,/ELsTifJ2lu4vsMhoHeZ5EnncHw.jpg,"['Comedy', 'Fantasy', 'Science Fiction']",https://www.warnerbros.com/movies/mars-attacks/,tt0116996,en,Mars Attacks!,A fleet of Martian spacecraft surrounds the wo...,21.051,/hll4O5vSAfnZDb6JbnP06GPtz7b.jpg,...,1996-12-12,106,"['en', 'fr']",Released,Nice planet. We'll take it!,Mars Attacks!,False,6.394,"['Tim Burton Productions', 'Warner Bros. Pictu...","['', 'US']"
77,False,/2eBL3wXDZqemW8SJ1RNxqtx6bgJ.jpg,"['Comedy', 'Drama', 'Mystery']",NaN,tt0111507,fr,Trois couleurs : Blanc,Polish immigrant Karol Karol finds himself out...,13.473,/fdIet3NSa27gobMbaUml66oCQNT.jpg,...,1994-01-26,92,"['fr', 'hu', 'pl']",Released,NaN,Three Colors: White,False,7.482,"['Le Studio Canal+', 'France 3 Cinéma', 'Eurim...","['FR', 'FR', 'FR', 'US']"

In [14]:
tmdb_1.head(2)

,adult,backdrop_path,genres,homepage,imdb_id,original_language,original_title,overview,popularity,poster_path,...,release_date,runtime,spoken_languages,status,tagline,title,video,vote_average,production_companies_name,production_companies_country
44,False,/ELsTifJ2lu4vsMhoHeZ5EnncHw.jpg,"['Comedy', 'Fantasy', 'Science Fiction']",https://www.warnerbros.com/movies/mars-attacks/,tt0116996,en,Mars Attacks!,A fleet of Martian spacecraft surrounds the wo...,21.051,/hll4O5vSAfnZDb6JbnP06GPtz7b.jpg,...,1996-12-12,106,"['en', 'fr']",Released,Nice planet. We'll take it!,Mars Attacks!,False,6.394,"['Tim Burton Productions', 'Warner Bros. Pictu...","['', 'US']"
77,False,/2eBL3wXDZqemW8SJ1RNxqtx6bgJ.jpg,"['Comedy', 'Drama', 'Mystery']",NaN,tt0111507,fr,Trois couleurs : Blanc,Polish immigrant Karol Karol finds himself out...,13.473,/fdIet3NSa27gobMbaUml66oCQNT.jpg,...,1994-01-26,92,"['fr', 'hu', 'pl']",Released,NaN,Three Colors: White,False,7.482,"['Le Studio Canal+', 'France 3 Cinéma', 'Eurim...","['FR', 'FR', 'FR', 'US']"

In [15]:
# Convertir 'release_date' en format datetime (si ce n'est pas déjà fait)
tmdb_1['release_date'] = pd.to_datetime(tmdb_1['release_date'], errors='coerce')

# Extraire l'année de la colonne 'release_date'
tmdb_1['release_year'] = tmdb_1['release_date'].dt.year

# Afficher les premières lignes pour vérifier le résultat
print(tmdb_1[['release_date', 'release_year']].head())

    release_date  release_year
44    1996-12-12        1996.0
77    1994-01-26        1994.0
102   1993-02-11        1993.0
130   1980-12-17        1980.0
135   1982-12-08        1982.0

In [16]:
tmdb_1.head(2)

,adult,backdrop_path,genres,homepage,imdb_id,original_language,original_title,overview,popularity,poster_path,...,runtime,spoken_languages,status,tagline,title,video,vote_average,production_companies_name,production_companies_country,release_year
44,False,/ELsTifJ2lu4vsMhoHeZ5EnncHw.jpg,"['Comedy', 'Fantasy', 'Science Fiction']",https://www.warnerbros.com/movies/mars-attacks/,tt0116996,en,Mars Attacks!,A fleet of Martian spacecraft surrounds the wo...,21.051,/hll4O5vSAfnZDb6JbnP06GPtz7b.jpg,...,106,"['en', 'fr']",Released,Nice planet. We'll take it!,Mars Attacks!,False,6.394,"['Tim Burton Productions', 'Warner Bros. Pictu...","['', 'US']",1996.0
77,False,/2eBL3wXDZqemW8SJ1RNxqtx6bgJ.jpg,"['Comedy', 'Drama', 'Mystery']",NaN,tt0111507,fr,Trois couleurs : Blanc,Polish immigrant Karol Karol finds himself out...,13.473,/fdIet3NSa27gobMbaUml66oCQNT.jpg,...,92,"['fr', 'hu', 'pl']",Released,NaN,Three Colors: White,False,7.482,"['Le Studio Canal+', 'France 3 Cinéma', 'Eurim...","['FR', 'FR', 'FR', 'US']",1994.0

In [17]:
# Filtrer les lignes où 'release_year' est supérieur ou égal à 1990
tmdb_90 = tmdb_1[tmdb_1['release_year'] >= 1990]

tmdb_90.shape

(4080, 22)

In [18]:
tmdb_90.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4080 entries, 44 to 308128
Data columns (total 22 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   adult                         4080 non-null   bool
 1   backdrop_path                 2993 non-null   object
 2   genres                        4080 non-null   object
 3   homepage                      509 non-null    object
 4   imdb_id                       4080 non-null   object
 5   original_language             4080 non-null   object
 6   original_title                4080 non-null   object
 7   overview                      3661 non-null   object
 8   popularity                    4080 non-null   float64
 9   poster_path                   3930 non-null   object
 10  production_countries          4080 non-null   object
 11  release_date                  4080 non-null   datetime64[ns]
 12  runtime                       4080 non-null   int64
 13  spoken_languages              4080 non-null   object
 14  status                        4080 non-null   object
 15  tagline                       664 non-null    object
 16  title                         4080 non-null   object
 17  video                         4080 non-null   bool
 18  vote_average                  4080 non-null   float64
 19  production_companies_name     4080 non-null   object
 20  production_companies_country  2210 non-null   object
 21  release_year                  4080 non-null   float64
dtypes: bool(2), datetime64[ns](1), float64(3), int64(1), object(15)
memory usage: 677.3+ KB

In [19]:
# ID du fichier Google Drive
file_id_table = '1BgXeRjXAJyZrAMY0oP3Y5pJ0xIW1clzf'

# URL pour télécharger le fichier
url_table = f'https://drive.google.com/uc?id={file_id_table}'

# Chemin de sauvegarde du fichier téléchargé
output = 'table_principale.csv'

# Télécharger le fichier
gdown.download(url_table, output, quiet=False)

# Lire le fichier CSV avec pandas
try:
    df_table = pd.read_csv(output, delimiter=',', on_bad_lines='skip', engine='python')
    if df_table.empty:
        print("Le fichier est vide.")
    else:
        # Afficher les premières lignes du DataFrame
        display(df_table.head())
except pd.errors.EmptyDataError:
    print("Aucune donnée à analyser dans le fichier.")
except Exception as e:
    print(f"Une erreur est survenue : {e}")

Downloading...
From: https://drive.google.com/uc?id=1BgXeRjXAJyZrAMY0oP3Y5pJ0xIW1clzf
To: /content/table_principale.csv
100%|██████████| 1.29M/1.29M [00:00<00:00, 121MB/s]

,tconst,averageRating,numVotes,ordering,nconst,category,title,language,types,startYear,runtimeMinutes,genres,primaryName,birthYear
0,tt0139645,6.400675,54558.048108,1.0,nm0000103,actress,Life in the Fast Lane,en,imdbDisplay,1998.0,92.0,Comedy,Fairuza Balk,1974.0
1,tt0119304,5.100000,9061.000000,1.0,nm0000106,actress,Home Fries,en,imdbDisplay,1998.0,91.0,"Comedy,Drama,Romance",Drew Barrymore,1975.0
2,tt0120523,6.400675,54558.048108,1.0,nm0000106,actress,Wishful Thinking,en,imdbDisplay,1997.0,93.0,"Comedy,Romance",Drew Barrymore,1975.0
3,tt0151738,6.000000,99378.000000,1.0,nm0000106,actress,Never Been Kissed,en,imdbDisplay,1999.0,107.0,"Comedy,Drama,Romance",Drew Barrymore,1975.0
4,tt0200027,6.500000,30914.000000,1.0,nm0000106,actress,Riding in Cars with Boys,en,imdbDisplay,2001.0,132.0,"Biography,Comedy,Drama",Drew Barrymore,1975.0

In [20]:
# Renommer les colonnes
tmdb_90.rename(columns={'imdb_id': 'tconst', 'title': 'title_imdb'}, inplace=True)

# Afficher les premières lignes pour vérifier le changement
display(tmdb_90.head())

<ipython-input-20-a1e331281a12>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmdb_90.rename(columns={'imdb_id': 'tconst', 'title': 'title_imdb'}, inplace=True)

,adult,backdrop_path,genres,homepage,tconst,original_language,original_title,overview,popularity,poster_path,...,runtime,spoken_languages,status,tagline,title_imdb,video,vote_average,production_companies_name,production_companies_country,release_year
44,False,/ELsTifJ2lu4vsMhoHeZ5EnncHw.jpg,"['Comedy', 'Fantasy', 'Science Fiction']",https://www.warnerbros.com/movies/mars-attacks/,tt0116996,en,Mars Attacks!,A fleet of Martian spacecraft surrounds the wo...,21.051,/hll4O5vSAfnZDb6JbnP06GPtz7b.jpg,...,106,"['en', 'fr']",Released,Nice planet. We'll take it!,Mars Attacks!,False,6.394,"['Tim Burton Productions', 'Warner Bros. Pictu...","['', 'US']",1996.0
77,False,/2eBL3wXDZqemW8SJ1RNxqtx6bgJ.jpg,"['Comedy', 'Drama', 'Mystery']",NaN,tt0111507,fr,Trois couleurs : Blanc,Polish immigrant Karol Karol finds himself out...,13.473,/fdIet3NSa27gobMbaUml66oCQNT.jpg,...,92,"['fr', 'hu', 'pl']",Released,NaN,Three Colors: White,False,7.482,"['Le Studio Canal+', 'France 3 Cinéma', 'Eurim...","['FR', 'FR', 'FR', 'US']",1994.0
102,False,/oT9diLGD1cgPdvkxqHIJcuSXKUT.jpg,"['Romance', 'Fantasy', 'Drama', 'Comedy']",NaN,tt0107048,en,Groundhog Day,"A narcissistic TV weatherman, along with his a...",21.795,/qIwyDf5k0eNsrfQjd0HCkeraNGD.jpg,...,101,"['en', 'fr', 'it']",Released,He’s having the worst day of his life… Over an...,Groundhog Day,False,7.603,['Columbia Pictures'],['US'],1993.0
155,False,/9Y9K6LeLrMeofOvX7hZW36Aj3OG.jpg,"['Comedy', 'Romance']",https://www.miramax.com/movie/amelie/,tt0211915,fr,Le Fabuleux Destin d'Amélie Poulain,"At a tiny Parisian café, the adorable yet pain...",26.104,/oTKduWL2tpIKEmkAqF4mFEAWAsv.jpg,...,122,"['fr', 'ru']",Released,One person can change your life forever.,Amélie,False,7.902,"['France 3 Cinéma', 'Claudie Ossard Production...","['FR', '', '', '', '', '', 'FR', 'DE', 'FR', '...",2001.0
251,False,/bHePzkyRcMhnab2qZbhj1bCElnf.jpg,"['Comedy', 'Drama', 'Fantasy']",http://www.lasciencedesreves-lefilm.com/accuei...,tt0354899,fr,La Science des rêves,A man entranced by his dreams and imagination ...,8.741,/1qCq228LsNtUseCnNE7Naw6NBUz.jpg,...,105,"['en', 'fr', 'es']",Released,Close your eyes. Open your heart.,The Science of Sleep,False,7.052,"['Partizan Films', 'Gaumont', 'France 3 Cinéma...","['', 'FR', 'FR', 'FR', 'IT', 'FR']",2006.0

In [21]:
# Fusionner les deux DataFrames sur la colonne 'tconst'
merged_df = pd.merge(tmdb_90, df_table, on='tconst', how='outer')

# Afficher les premières lignes pour vérifier la fusion
display(merged_df.head())

,adult,backdrop_path,genres_x,homepage,tconst,original_language,original_title,overview,popularity,poster_path,...,nconst,category,title,language,types,startYear,runtimeMinutes,genres_y,primaryName,birthYear
0,False,/hfeiSfWYujh6MKhtGTXyK3DD4nN.jpg,"['Romance', 'Fantasy', 'Comedy']",NaN,tt0035423,en,Kate & Leopold,When her scientist ex-boyfriend discovers a po...,15.770,/mUvikzKJJSg9khrVdxK8kg3TMHA.jpg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,tt0096222,NaN,NaN,NaN,NaN,NaN,...,nm0510903,actor,To Miss with Love,en,imdbDisplay,1992.0,90.0,"Comedy,Drama,Romance",Jimmy Lin,1974.0
2,False,/6tRdTNdcmdBlTGyJ924ISyJDABA.jpg,"['Comedy', 'Drama', 'Romance']",NaN,tt0097106,fr,Conte de printemps,The story of an introverted young girl just r...,9.163,/bP2qpuzQPBBBJa4kOhvLvOOiASq.jpg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,False,/uEPLeurEn2dp54f5owtMC3PeiPN.jpg,"['Crime', 'Action', 'Adventure']",NaN,tt0097318,en,Eye of the Widow,A new international terrorist group attack the...,0.742,/1Ela9pkCRCPugwasp8hdR1BpfXb.jpg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,False,/inHgpiOAddL4Y53EvHf9B5lf2Sc.jpg,"['Drama', 'Adventure']",NaN,tt0097462,fr,Guerriers et Captives,"Patagonia, Argentina, 1880s. During the Conque...",0.960,/ytYs98qqVmiY45cxkqNgJbj8uDL.jpg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12379 entries, 0 to 12378
Data columns (total 35 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   adult                         4080 non-null   object
 1   backdrop_path                 2993 non-null   object
 2   genres_x                      4080 non-null   object
 3   homepage                      509 non-null    object
 4   tconst                        12379 non-null  object
 5   original_language             4080 non-null   object
 6   original_title                4080 non-null   object
 7   overview                      3661 non-null   object
 8   popularity                    4080 non-null   float64
 9   poster_path                   3930 non-null   object
 10  production_countries          4080 non-null   object
 11  release_date                  4080 non-null   datetime64[ns]
 12  runtime                       4080 non-null   float64
 13  spoken_languages              4080 non-null   object
 14  status                        4080 non-null   object
 15  tagline                       664 non-null    object
 16  title_imdb                    4080 non-null   object
 17  video                         4080 non-null   object
 18  vote_average                  4080 non-null   float64
 19  production_companies_name     4080 non-null   object
 20  production_companies_country  2210 non-null   object
 21  release_year                  4080 non-null   float64
 22  averageRating                 8917 non-null   float64
 23  numVotes                      8917 non-null   float64
 24  ordering                      8917 non-null   float64
 25  nconst                        8917 non-null   object
 26  category                      8917 non-null   object
 27  title                         8917 non-null   object
 28  language                      8917 non-null   object
 29  types                         8917 non-null   object
 30  startYear                     8917 non-null   float64
 31  runtimeMinutes                8917 non-null   float64
 32  genres_y                      8917 non-null   object
 33  primaryName                   8917 non-null   object
 34  birthYear                     8917 non-null   float64
dtypes: datetime64[ns](1), float64(10), object(24)
memory usage: 3.3+ MB

In [23]:
merged_df.columns

Index(['adult', 'backdrop_path', 'genres_x', 'homepage', 'tconst',
       'original_language', 'original_title', 'overview', 'popularity',
       'poster_path', 'production_countries', 'release_date', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title_imdb', 'video',
       'vote_average', 'production_companies_name',
       'production_companies_country', 'release_year', 'averageRating',
       'numVotes', 'ordering', 'nconst', 'category', 'title', 'language',
       'types', 'startYear', 'runtimeMinutes', 'genres_y', 'primaryName',
       'birthYear'],
      dtype='object')

In [24]:
# Combiner les valeurs des deux colonnes 'genre' en une seule
merged_df['genres'] = merged_df['genres_x'].fillna('') + ',' + merged_df['genres_y'].fillna('')

In [25]:
# Supprimer les colonnes supplémentaires 'genre_tmdb' et 'genre_table'
merged_df = merged_df.drop(columns=['genres_x', 'genres_y'])

# Afficher les premières lignes pour vérifier la fusion
display(merged_df.head())

,adult,backdrop_path,homepage,tconst,original_language,original_title,overview,popularity,poster_path,production_countries,...,nconst,category,title,language,types,startYear,runtimeMinutes,primaryName,birthYear,genres
0,False,/hfeiSfWYujh6MKhtGTXyK3DD4nN.jpg,NaN,tt0035423,en,Kate & Leopold,When her scientist ex-boyfriend discovers a po...,15.770,/mUvikzKJJSg9khrVdxK8kg3TMHA.jpg,['US'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['Romance', 'Fantasy', 'Comedy'],"
1,NaN,NaN,NaN,tt0096222,NaN,NaN,NaN,NaN,NaN,NaN,...,nm0510903,actor,To Miss with Love,en,imdbDisplay,1992.0,90.0,Jimmy Lin,1974.0,",Comedy,Drama,Romance"
2,False,/6tRdTNdcmdBlTGyJ924ISyJDABA.jpg,NaN,tt0097106,fr,Conte de printemps,The story of an introverted young girl just r...,9.163,/bP2qpuzQPBBBJa4kOhvLvOOiASq.jpg,['FR'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['Comedy', 'Drama', 'Romance'],"
3,False,/uEPLeurEn2dp54f5owtMC3PeiPN.jpg,NaN,tt0097318,en,Eye of the Widow,A new international terrorist group attack the...,0.742,/1Ela9pkCRCPugwasp8hdR1BpfXb.jpg,"['ES', 'FR']",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['Crime', 'Action', 'Adventure'],"
4,False,/inHgpiOAddL4Y53EvHf9B5lf2Sc.jpg,NaN,tt0097462,fr,Guerriers et Captives,"Patagonia, Argentina, 1880s. During the Conque...",0.960,/ytYs98qqVmiY45cxkqNgJbj8uDL.jpg,"['AR', 'FR', 'CH']",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['Drama', 'Adventure'],"

In [26]:
merged_df.shape

(12379, 34)

In [27]:
# Trouver les NaN dans tout le DataFrame
nan_counts = merged_df.isna().sum()

# Afficher le nombre de NaN par colonne
print(nan_counts)

adult                            8299
backdrop_path                    9386
homepage                        11870
tconst                              0
original_language                8299
original_title                   8299
overview                         8718
popularity                       8299
poster_path                      8449
production_countries             8299
release_date                     8299
runtime                          8299
spoken_languages                 8299
status                           8299
tagline                         11715
title_imdb                       8299
video                            8299
vote_average                     8299
production_companies_name        8299
production_companies_country    10169
release_year                     8299
averageRating                    3462
numVotes                         3462
ordering                         3462
nconst                           3462
category                         3462
title                            3462
language                         3462
types                            3462
startYear                        3462
runtimeMinutes                   3462
primaryName                      3462
birthYear                        3462
genres                              0
dtype: int64

Supprimer les colonnes 'homepage', 'tagline', 'production_companies_country' car nombre de NaN > 10000

In [28]:
# Supprimer les colonnes spécifiées
merged_df = merged_df.drop(columns=['homepage', 'tagline', 'production_companies_country'])

In [29]:
# Combiner les colonnes 'title_imdb' et 'title' en une seule colonne
#merged_df['titles'] = merged_df['title_imdb'].fillna('') + ' - ' + merged_df['title'].fillna('')

# Supprimer les colonnes 'title_imdb' et 'title'
#merged_df = merged_df.drop(columns=['title_imdb', 'title'])

# Afficher les premières lignes pour vérifier
display(merged_df.head())

,adult,backdrop_path,tconst,original_language,original_title,overview,popularity,poster_path,production_countries,release_date,...,nconst,category,title,language,types,startYear,runtimeMinutes,primaryName,birthYear,genres
0,False,/hfeiSfWYujh6MKhtGTXyK3DD4nN.jpg,tt0035423,en,Kate & Leopold,When her scientist ex-boyfriend discovers a po...,15.770,/mUvikzKJJSg9khrVdxK8kg3TMHA.jpg,['US'],2001-12-25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['Romance', 'Fantasy', 'Comedy'],"
1,NaN,NaN,tt0096222,NaN,NaN,NaN,NaN,NaN,NaN,NaT,...,nm0510903,actor,To Miss with Love,en,imdbDisplay,1992.0,90.0,Jimmy Lin,1974.0,",Comedy,Drama,Romance"
2,False,/6tRdTNdcmdBlTGyJ924ISyJDABA.jpg,tt0097106,fr,Conte de printemps,The story of an introverted young girl just r...,9.163,/bP2qpuzQPBBBJa4kOhvLvOOiASq.jpg,['FR'],1990-04-04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['Comedy', 'Drama', 'Romance'],"
3,False,/uEPLeurEn2dp54f5owtMC3PeiPN.jpg,tt0097318,en,Eye of the Widow,A new international terrorist group attack the...,0.742,/1Ela9pkCRCPugwasp8hdR1BpfXb.jpg,"['ES', 'FR']",1991-10-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['Crime', 'Action', 'Adventure'],"
4,False,/inHgpiOAddL4Y53EvHf9B5lf2Sc.jpg,tt0097462,fr,Guerriers et Captives,"Patagonia, Argentina, 1880s. During the Conque...",0.960,/ytYs98qqVmiY45cxkqNgJbj8uDL.jpg,"['AR', 'FR', 'CH']",1990-09-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['Drama', 'Adventure'],"

In [30]:
merged_df.columns

Index(['adult', 'backdrop_path', 'tconst', 'original_language',
       'original_title', 'overview', 'popularity', 'poster_path',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'title_imdb', 'video', 'vote_average',
       'production_companies_name', 'release_year', 'averageRating',
       'numVotes', 'ordering', 'nconst', 'category', 'title', 'language',
       'types', 'startYear', 'runtimeMinutes', 'primaryName', 'birthYear',
       'genres'],
      dtype='object')

In [31]:
# Trouver les NaN dans tout le DataFrame
nan_counts = merged_df.isna().sum()

# Afficher le nombre de NaN par colonne
print(nan_counts)

adult                        8299
backdrop_path                9386
tconst                          0
original_language            8299
original_title               8299
overview                     8718
popularity                   8299
poster_path                  8449
production_countries         8299
release_date                 8299
runtime                      8299
spoken_languages             8299
status                       8299
title_imdb                   8299
video                        8299
vote_average                 8299
production_companies_name    8299
release_year                 8299
averageRating                3462
numVotes                     3462
ordering                     3462
nconst                       3462
category                     3462
title                        3462
language                     3462
types                        3462
startYear                    3462
runtimeMinutes               3462
primaryName                  3462
birthYear                    3462
genres                          0
dtype: int64

In [32]:
# Combiner les colonnes 'spoken_languages' et 'language' en une seule colonne
merged_df['languages_combined'] = merged_df['spoken_languages'].fillna('') + ', ' + merged_df['language'].fillna('')

# Supprimer les colonnes 'spoken_languages' et 'language'
merged_df = merged_df.drop(columns=['spoken_languages', 'language'])

# Afficher les premières lignes pour vérifier
display(merged_df.head())

,adult,backdrop_path,tconst,original_language,original_title,overview,popularity,poster_path,production_countries,release_date,...,nconst,category,title,types,startYear,runtimeMinutes,primaryName,birthYear,genres,languages_combined
0,False,/hfeiSfWYujh6MKhtGTXyK3DD4nN.jpg,tt0035423,en,Kate & Leopold,When her scientist ex-boyfriend discovers a po...,15.770,/mUvikzKJJSg9khrVdxK8kg3TMHA.jpg,['US'],2001-12-25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['Romance', 'Fantasy', 'Comedy'],","['en', 'fr', 'it'],"
1,NaN,NaN,tt0096222,NaN,NaN,NaN,NaN,NaN,NaN,NaT,...,nm0510903,actor,To Miss with Love,imdbDisplay,1992.0,90.0,Jimmy Lin,1974.0,",Comedy,Drama,Romance",", en"
2,False,/6tRdTNdcmdBlTGyJ924ISyJDABA.jpg,tt0097106,fr,Conte de printemps,The story of an introverted young girl just r...,9.163,/bP2qpuzQPBBBJa4kOhvLvOOiASq.jpg,['FR'],1990-04-04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['Comedy', 'Drama', 'Romance'],","['fr'],"
3,False,/uEPLeurEn2dp54f5owtMC3PeiPN.jpg,tt0097318,en,Eye of the Widow,A new international terrorist group attack the...,0.742,/1Ela9pkCRCPugwasp8hdR1BpfXb.jpg,"['ES', 'FR']",1991-10-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['Crime', 'Action', 'Adventure'],","['ar', 'en', 'fr', 'es'],"
4,False,/inHgpiOAddL4Y53EvHf9B5lf2Sc.jpg,tt0097462,fr,Guerriers et Captives,"Patagonia, Argentina, 1880s. During the Conque...",0.960,/ytYs98qqVmiY45cxkqNgJbj8uDL.jpg,"['AR', 'FR', 'CH']",1990-09-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['Drama', 'Adventure'],","['fr', 'es'],"

In [33]:
# Trouver les NaN dans tout le DataFrame
nan_counts = merged_df.isna().sum()

# Afficher le nombre de NaN par colonne
print(nan_counts)

adult                        8299
backdrop_path                9386
tconst                          0
original_language            8299
original_title               8299
overview                     8718
popularity                   8299
poster_path                  8449
production_countries         8299
release_date                 8299
runtime                      8299
status                       8299
title_imdb                   8299
video                        8299
vote_average                 8299
production_companies_name    8299
release_year                 8299
averageRating                3462
numVotes                     3462
ordering                     3462
nconst                       3462
category                     3462
title                        3462
types                        3462
startYear                    3462
runtimeMinutes               3462
primaryName                  3462
birthYear                    3462
genres                          0
languages_combined              0
dtype: int64

In [34]:
# Combiner les colonnes 'vote_average' et 'numVotes' en une seule colonne
merged_df['votes'] = merged_df['vote_average'].fillna('').astype(str) + ' / ' + merged_df['numVotes'].fillna('').astype(str)

# Supprimer les colonnes 'vote_average' et 'numVotes'
merged_df = merged_df.drop(columns=['vote_average', 'numVotes'])

# Afficher les premières lignes pour vérifier
display(merged_df.head())

,adult,backdrop_path,tconst,original_language,original_title,overview,popularity,poster_path,production_countries,release_date,...,category,title,types,startYear,runtimeMinutes,primaryName,birthYear,genres,languages_combined,votes
0,False,/hfeiSfWYujh6MKhtGTXyK3DD4nN.jpg,tt0035423,en,Kate & Leopold,When her scientist ex-boyfriend discovers a po...,15.770,/mUvikzKJJSg9khrVdxK8kg3TMHA.jpg,['US'],2001-12-25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['Romance', 'Fantasy', 'Comedy'],","['en', 'fr', 'it'],",6.326 /
1,NaN,NaN,tt0096222,NaN,NaN,NaN,NaN,NaN,NaN,NaT,...,actor,To Miss with Love,imdbDisplay,1992.0,90.0,Jimmy Lin,1974.0,",Comedy,Drama,Romance",", en",/ 54558.04810794954
2,False,/6tRdTNdcmdBlTGyJ924ISyJDABA.jpg,tt0097106,fr,Conte de printemps,The story of an introverted young girl just r...,9.163,/bP2qpuzQPBBBJa4kOhvLvOOiASq.jpg,['FR'],1990-04-04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['Comedy', 'Drama', 'Romance'],","['fr'],",6.9 /
3,False,/uEPLeurEn2dp54f5owtMC3PeiPN.jpg,tt0097318,en,Eye of the Widow,A new international terrorist group attack the...,0.742,/1Ela9pkCRCPugwasp8hdR1BpfXb.jpg,"['ES', 'FR']",1991-10-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['Crime', 'Action', 'Adventure'],","['ar', 'en', 'fr', 'es'],",3.0 /
4,False,/inHgpiOAddL4Y53EvHf9B5lf2Sc.jpg,tt0097462,fr,Guerriers et Captives,"Patagonia, Argentina, 1880s. During the Conque...",0.960,/ytYs98qqVmiY45cxkqNgJbj8uDL.jpg,"['AR', 'FR', 'CH']",1990-09-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['Drama', 'Adventure'],","['fr', 'es'],",0.0 /

In [35]:
# Combiner les colonnes 'runtimeMinutes' et 'runtime' en une seule colonne
merged_df['runtime_combined'] = merged_df['runtimeMinutes'].fillna('').astype(str) + ' / ' + merged_df['runtime'].fillna('').astype(str)

# Supprimer les colonnes 'runtimeMinutes' et 'runtime'
merged_df = merged_df.drop(columns=['runtimeMinutes', 'runtime'])

# Afficher les premières lignes pour vérifier
display(merged_df.head())

,adult,backdrop_path,tconst,original_language,original_title,overview,popularity,poster_path,production_countries,release_date,...,category,title,types,startYear,primaryName,birthYear,genres,languages_combined,votes,runtime_combined
0,False,/hfeiSfWYujh6MKhtGTXyK3DD4nN.jpg,tt0035423,en,Kate & Leopold,When her scientist ex-boyfriend discovers a po...,15.770,/mUvikzKJJSg9khrVdxK8kg3TMHA.jpg,['US'],2001-12-25,...,NaN,NaN,NaN,NaN,NaN,NaN,"['Romance', 'Fantasy', 'Comedy'],","['en', 'fr', 'it'],",6.326 /,/ 118.0
1,NaN,NaN,tt0096222,NaN,NaN,NaN,NaN,NaN,NaN,NaT,...,actor,To Miss with Love,imdbDisplay,1992.0,Jimmy Lin,1974.0,",Comedy,Drama,Romance",", en",/ 54558.04810794954,90.0 /
2,False,/6tRdTNdcmdBlTGyJ924ISyJDABA.jpg,tt0097106,fr,Conte de printemps,The story of an introverted young girl just r...,9.163,/bP2qpuzQPBBBJa4kOhvLvOOiASq.jpg,['FR'],1990-04-04,...,NaN,NaN,NaN,NaN,NaN,NaN,"['Comedy', 'Drama', 'Romance'],","['fr'],",6.9 /,/ 103.0
3,False,/uEPLeurEn2dp54f5owtMC3PeiPN.jpg,tt0097318,en,Eye of the Widow,A new international terrorist group attack the...,0.742,/1Ela9pkCRCPugwasp8hdR1BpfXb.jpg,"['ES', 'FR']",1991-10-17,...,NaN,NaN,NaN,NaN,NaN,NaN,"['Crime', 'Action', 'Adventure'],","['ar', 'en', 'fr', 'es'],",3.0 /,/ 95.0
4,False,/inHgpiOAddL4Y53EvHf9B5lf2Sc.jpg,tt0097462,fr,Guerriers et Captives,"Patagonia, Argentina, 1880s. During the Conque...",0.960,/ytYs98qqVmiY45cxkqNgJbj8uDL.jpg,"['AR', 'FR', 'CH']",1990-09-05,...,NaN,NaN,NaN,NaN,NaN,NaN,"['Drama', 'Adventure'],","['fr', 'es'],",0.0 /,/ 99.0

In [36]:
# Renommer la colonne 'runtime_combined' en 'runtime'
merged_df = merged_df.rename(columns={'runtime_combined': 'runtime'})

In [37]:
# Combiner les colonnes 'release_year' et 'startYear' en une seule colonne
merged_df['start_year'] = merged_df['release_year'].fillna('').astype(str) + ' - ' + merged_df['startYear'].fillna('').astype(str)

# Supprimer les colonnes 'release_year' et 'startYear'
merged_df = merged_df.drop(columns=['release_year', 'startYear'])

# Afficher les premières lignes pour vérifier
display(merged_df.head(2))

,adult,backdrop_path,tconst,original_language,original_title,overview,popularity,poster_path,production_countries,release_date,...,category,title,types,primaryName,birthYear,genres,languages_combined,votes,runtime,start_year
0,False,/hfeiSfWYujh6MKhtGTXyK3DD4nN.jpg,tt0035423,en,Kate & Leopold,When her scientist ex-boyfriend discovers a po...,15.77,/mUvikzKJJSg9khrVdxK8kg3TMHA.jpg,['US'],2001-12-25,...,NaN,NaN,NaN,NaN,NaN,"['Romance', 'Fantasy', 'Comedy'],","['en', 'fr', 'it'],",6.326 /,/ 118.0,2001.0 -
1,NaN,NaN,tt0096222,NaN,NaN,NaN,NaN,NaN,NaN,NaT,...,actor,To Miss with Love,imdbDisplay,Jimmy Lin,1974.0,",Comedy,Drama,Romance",", en",/ 54558.04810794954,90.0 /,- 1992.0

Supression des colonnes 'nconst', 'release_date'

In [38]:
merged_df = merged_df.drop(columns=['nconst', 'release_date'])

In [39]:
# Obtenir les valeurs uniques dans la colonne 'video'
video_unik = merged_df['video'].unique()
print(video_unik)

[False nan True]

In [40]:
#Supression de la colonnes 'video'
#merged_df = merged_df.drop(columns=['video'])

In [41]:
#Supression des colonnes spécifiées
#merged_df = merged_df.drop(columns=['original_language','original_title', 'types'])

In [42]:
# Renommer la colonne 'languages_combined' en 'spoken_languages'
merged_df = merged_df.rename(columns={'languages_combined': 'spoken_languages'})

In [43]:
# Trouver la médiane de la colonne 'averageRating'
median_value = merged_df['averageRating'].median()

# Remplacer les NaN par la médiane
merged_df['averageRating'] = merged_df['averageRating'].fillna(median_value)

# Vérifier que les NaN ont été remplacés
display(merged_df['averageRating'].head())

0    6.400675
1    6.400675
2    6.400675
3    6.400675
4    6.400675
Name: averageRating, dtype: float64

In [44]:
# Trouver la valeur la plus fréquente (mode) dans la colonne 'production_countries'
most_frequent_value = merged_df['production_countries'].mode()[0]

# Remplacer les NaN par la valeur la plus fréquente
merged_df['production_countries'] = merged_df['production_countries'].fillna(most_frequent_value)

# Vérifier que les NaN ont été remplacés
display(merged_df['production_countries'].head())

0                ['US']
1                ['FR']
2                ['FR']
3          ['ES', 'FR']
4    ['AR', 'FR', 'CH']
Name: production_countries, dtype: object

In [45]:
# Trouver la valeur la plus fréquente (mode) dans la colonne 'production_companies_name '
most_companies = merged_df['production_companies_name'].mode()[0]

# Remplacer les NaN par la valeur la plus fréquente
merged_df['production_companies_name'] = merged_df['production_companies_name'].fillna(most_companies)

# Vérifier que les NaN ont été remplacés
display(merged_df['production_companies_name'].head(2))

0    ['Konrad Pictures', 'Miramax']
1                                []
Name: production_companies_name, dtype: object

In [46]:
# Trouver la valeur la plus fréquente (mode) dans la colonne 'category'
most_frequent_category = merged_df['category'].mode()[0]

# Remplacer les NaN par la valeur la plus fréquente
merged_df['category'] = merged_df['category'].fillna(most_frequent_category)

# Vérifier le remplacement
display(merged_df[['category', 'primaryName']].head())

  category primaryName
0    actor         NaN
1    actor   Jimmy Lin
2    actor         NaN
3    actor         NaN
4    actor         NaN

In [47]:
# Remplacer les NaN dans 'primaryName' par 'Unknown'
merged_df['primaryName'] = merged_df['primaryName'].fillna('Unknown')

# Vérifier le remplacement
display(merged_df[['category', 'primaryName']].head())

  category primaryName
0    actor     Unknown
1    actor   Jimmy Lin
2    actor     Unknown
3    actor     Unknown
4    actor     Unknown

In [48]:
#Supression de la colonnes 'ordering'
merged_df = merged_df.drop(columns=['ordering'])

In [49]:
#Supression de la colonnes 'status'
merged_df = merged_df.drop(columns=['status'])

In [50]:
# Obtenir les valeurs uniques dans la colonne 'popularity'
popularity_unik = merged_df['popularity'].nunique()
print(popularity_unik)

2674

In [51]:
#Supression de la colonnes 'popularity'
merged_df = merged_df.drop(columns=['popularity'])

In [52]:
# Calculer la médiane de la colonne 'birthYear'
median_birth_year = merged_df['birthYear'].median()

# Remplacer les NaN par la médiane
merged_df['birthYear'] = merged_df['birthYear'].fillna(median_birth_year)

# Vérifier le remplacement
display(merged_df['birthYear'].head())

0    1981.0
1    1974.0
2    1981.0
3    1981.0
4    1981.0
Name: birthYear, dtype: float64

In [53]:
# Définir une phrase fun et originale
replacement_phrase = "Découvrez cette incroyable aventure et laissez-vous surprendre par chaque tournant inattendu !"

# Remplacer les NaN dans la colonne 'overview'
merged_df['overview'] = merged_df['overview'].fillna(replacement_phrase)

# Vérifier le remplacement
display(merged_df['overview'].head())

0    When her scientist ex-boyfriend discovers a po...
1    Découvrez cette incroyable aventure et laissez...
2    The story of an introverted young girl  just r...
3    A new international terrorist group attack the...
4    Patagonia, Argentina, 1880s. During the Conque...
Name: overview, dtype: object

Pour remplacer les valeurs manquantes dans la colonne 'adult', qui est un booléen indiquant si le film est pour adultes ou non, il est courant de choisir une valeur par défaut. Voici quelques approches possibles :

Remplacer par False (Non adulte) : C'est souvent une approche sûre car la majorité des films ne sont pas pour adultes.
Remplacer par True (Adulte) : Si vous pensez que la majorité des valeurs manquantes sont des films pour adultes (moins courant).
Analyser les données : Si possible, analyser les autres colonnes pour faire une supposition plus éclairée sur les valeurs manquantes.

In [54]:
# Remplacer les NaN dans la colonne 'adult' par False
merged_df['adult'] = merged_df['adult'].fillna(False)

<ipython-input-54-cd503225b961>:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  merged_df['adult'] = merged_df['adult'].fillna(False)

In [55]:
# Trouver les NaN dans tout le DataFrame
nan_counts = merged_df.isna().sum()

# Afficher le nombre de NaN par colonne
print(nan_counts)

adult                           0
backdrop_path                9386
tconst                          0
original_language            8299
original_title               8299
overview                        0
poster_path                  8449
production_countries            0
title_imdb                   8299
video                        8299
production_companies_name       0
averageRating                   0
category                        0
title                        3462
types                        3462
primaryName                     0
birthYear                       0
genres                          0
spoken_languages                0
votes                           0
runtime                         0
start_year                      0
dtype: int64

In [56]:
# Supprimer les lignes avec des valeurs NaN dans la colonne 'backdrop_path'
df_clean = merged_df.dropna(subset=['poster_path'])

In [57]:
# Trouver les NaN dans tout le DataFrame
nan_counts = df_clean.isna().sum()

# Afficher le nombre de NaN par colonne
print(nan_counts)

adult                           0
backdrop_path                 945
tconst                          0
original_language               0
original_title                  0
overview                        0
poster_path                     0
production_countries            0
title_imdb                      0
video                           0
production_companies_name       0
averageRating                   0
category                        0
title                        3313
types                        3313
primaryName                     0
birthYear                       0
genres                          0
spoken_languages                0
votes                           0
runtime                         0
start_year                      0
dtype: int64

In [58]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3930 entries, 0 to 12377
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   adult                      3930 non-null   bool
 1   backdrop_path              2985 non-null   object
 2   tconst                     3930 non-null   object
 3   original_language          3930 non-null   object
 4   original_title             3930 non-null   object
 5   overview                   3930 non-null   object
 6   poster_path                3930 non-null   object
 7   production_countries       3930 non-null   object
 8   title_imdb                 3930 non-null   object
 9   video                      3930 non-null   object
 10  production_companies_name  3930 non-null   object
 11  averageRating              3930 non-null   float64
 12  category                   3930 non-null   object
 13  title                      617 non-null    object
 14  types                      617 non-null    object
 15  primaryName                3930 non-null   object
 16  birthYear                  3930 non-null   float64
 17  genres                     3930 non-null   object
 18  spoken_languages           3930 non-null   object
 19  votes                      3930 non-null   object
 20  runtime                    3930 non-null   object
 21  start_year                 3930 non-null   object
dtypes: bool(1), float64(2), object(19)
memory usage: 679.3+ KB

In [59]:
# Supprimer la colonne 'backdrop_path'
final_df = df_clean.drop(columns=['backdrop_path'])

In [60]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3930 entries, 0 to 12377
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   adult                      3930 non-null   bool
 1   tconst                     3930 non-null   object
 2   original_language          3930 non-null   object
 3   original_title             3930 non-null   object
 4   overview                   3930 non-null   object
 5   poster_path                3930 non-null   object
 6   production_countries       3930 non-null   object
 7   title_imdb                 3930 non-null   object
 8   video                      3930 non-null   object
 9   production_companies_name  3930 non-null   object
 10  averageRating              3930 non-null   float64
 11  category                   3930 non-null   object
 12  title                      617 non-null    object
 13  types                      617 non-null    object
 14  primaryName                3930 non-null   object
 15  birthYear                  3930 non-null   float64
 16  genres                     3930 non-null   object
 17  spoken_languages           3930 non-null   object
 18  votes                      3930 non-null   object
 19  runtime                    3930 non-null   object
 20  start_year                 3930 non-null   object
dtypes: bool(1), float64(2), object(18)
memory usage: 648.6+ KB

In [63]:
# Extraire la colonne 'tconst' qui contient les IDs des films
movie_ids = final_df['tconst'].tolist()

# Afficher le nombre total d'IDs extraits
print(f"Nombre total de films : {len(movie_ids)}")

# Afficher les premiers IDs pour vérifier
print(movie_ids[:10])

Nombre total de films : 3930
['tt0035423', 'tt0097106', 'tt0097318', 'tt0097462', 'tt0097884', 'tt0097988', 'tt0098361', 'tt0098961', 'tt0099009', 'tt0099014']

In [70]:
import requests
import pandas as pd
from IPython.display import display, Image

# Configuration API
API_KEY = "ed5d65da6eaa9f2dec411dae1e19302d"
BASE_URL = "https://api.themoviedb.org/3"

# Fonction pour obtenir les détails d'un film
def get_movie_details(movie_id, api_key):
    url = f"{BASE_URL}/movie/{movie_id}?api_key={api_key}"
    response = requests.get(url)
    return response.json()

# Fonction pour construire l'URL de l'image
def get_image_url(poster_path, file_size='w200'):
    base_url = "https://image.tmdb.org/t/p/"
    return f"{base_url}{file_size}{poster_path}"

# Fonction pour récupérer l'affiche d'un film et construire l'URL de l'image
def get_movie_poster_url(movie_id, api_key, file_size='w154'):
    movie_details = get_movie_details(movie_id, api_key)
    poster_path = movie_details.get('poster_path', '')
    return get_image_url(poster_path, file_size) if poster_path else None

# Liste d'IDs de films
movie_ids = ['tt0035423', 'tt0097106', 'tt0097318']

# Récupérer les URLs des affiches pour les 10 premiers films
poster_urls = [get_movie_poster_url(movie_id, API_KEY) for movie_id in movie_ids]

# Afficher les affiches
for url in poster_urls:
    if url:
        display(Image(url=url))

In [76]:
# Ajouter une colonne 'poster_url' dans le DataFrame
final_df['poster_url'] = final_df['tconst'].apply(lambda x: get_movie_poster_url(x, API_KEY))

In [75]:
print(final_df[['tconst', 'original_language', 'original_title', 'poster_url']].head().to_markdown())

|    | tconst    | original_language   | original_title        | poster_url                                                      |
|---:|:----------|:--------------------|:----------------------|:----------------------------------------------------------------|
|  0 | tt0035423 | en                  | Kate & Leopold        | https://image.tmdb.org/t/p/w154/mUvikzKJJSg9khrVdxK8kg3TMHA.jpg |
|  2 | tt0097106 | fr                  | Conte de printemps    | https://image.tmdb.org/t/p/w154/2MDvnal22vJiGJuq2JQwmAFugKk.jpg |
|  3 | tt0097318 | en                  | Eye of the Widow      | https://image.tmdb.org/t/p/w154/2hCLBZ4NFlaYtEkXiwcitRCrfmv.jpg |
|  4 | tt0097462 | fr                  | Guerriers et Captives | https://image.tmdb.org/t/p/w154/ytYs98qqVmiY45cxkqNgJbj8uDL.jpg |
|  5 | tt0097884 | fr                  | Milou en Mai          | https://image.tmdb.org/t/p/w154/bnlsDTtlgvTnpLXg8iNav9b0xXE.jpg |